---
version: 1
subgraphs:
  - name: person
    routing_url: http://host.containers.internal:8001/graphql
    schema:
      file: ../../person-service/src/schema.gql
  - name: group
    routing_url: http://host.containers.internal:8002/graphql
    schema:
      file: ../../group-service/src/schema.gql
